# Railway deployment configuration
[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build:all"]

[start]
cmd = "NODE_ENV=production node dist/optimized-server.js"